const brands = [
    {
        alias: 'visa',
        name: 'Visa',
        codeName: 'CVV',
        codeLength: 3,
        gaps: [4, 8, 12],
        lengths: [16],
        pattern: /^4\d*$/,
    },
    {
        alias: 'master-card',
        name: 'MasterCard',
        codeName: 'CVC',
        codeLength: 3,
        gaps: [4, 8, 12],
        lengths: [16],
        pattern: /^(5[1-5]|222[1-9]|2[3-6]|27[0-1]|2720)\d*$/,
    },
    {
        alias: 'american-express',
        name: 'AmericanExpress',
        codeName: 'CID',
        codeLength: 4,
        gaps: [4, 10],
        lengths: [15],
        pattern: /^3[47]\d*$/,
    },
    {
        alias: 'diners-club',
        name: 'DinersClub',
        codeName: 'CVV',
        codeLength: 3,
        gaps: [4, 10],
        lengths: [14],
        pattern: /^3(0[0-5]|[689])\d*$/,
    },
    {
        alias: 'unionpay',
        name: 'UnionPay',
        codeName: 'CVN',
        codeLength: 3,
        gaps: [4, 8, 12],
        lengths: [16, 17, 18, 19],
        pattern: /^62[0-5]\d*$/,
    },
    {
        alias: 'maestro',
        name: 'Maestro',
        codeName: 'CVC',
        codeLength: 3,
        gaps: [4, 8, 12],
        lengths: [12, 13, 14, 15, 16, 17, 18, 19],
        pattern: /^(5[0678]|6304|6390|6054|6271|67)\d*$/,
    },
    {
        alias: 'mir',
        name: 'MIR',
        codeName: 'CVC',
        codeLength: 3,
        gaps: [4, 8, 12],
        lengths: [16],
        pattern: /^22\d*$/,
    },
];

export default brands;
